### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test target-iceberg

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - uses: hoverkraft-tech/compose-action@v2.1.0
      with:
        compose-file: "./docker-compose.yml"
        down-flags: "--remove-orphans"
        up-flags: "--no-start"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry env use ${{ matrix.python-version }}
        poetry install
    - name: Test with pytest
      run: |
        docker compose up -d
        poetry run  pytest
        docker compose down